version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: travel-itinerary-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - travel-network

  # FastAPI Application
  api:
    build: .
    container_name: travel-itinerary-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/travel_itinerary_db?authSource=admin
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    networks:
      - travel-network
    volumes:
      - ./logs:/app/logs

  # Streamlit Interface (optional)
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: travel-itinerary-ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    networks:
      - travel-network

volumes:
  mongodb_data:
    driver: local

networks:
  travel-network:
    driver: bridge 